# Generated by Django 6.1 on 2026-09-20 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('staffs', '0002_alter_staff_gender_alter_staff_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='linked_staff',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_profile', to='staffs.staff'),
        ),
    ]
